- hosts: localhost
  gather_facts: false
  vars_files:
    - vars.yml

  tasks:
    - name: Create Web Security Group
      amazon.aws.ec2_security_group:
        name: "{{ web_sg_name }}"
        description: "Security group for web server"
        region: "{{ aws_region }}"
        vpc_id: "{{ vpc_id }}"
        rules:
          - proto: tcp
            ports:
              - 22
              - 80
            cidr_ip: 0.0.0.0/0
      register: web_sg

    - name: Launch EC2 instance
      amazon.aws.ec2_instance:
        name: web-server
        key_name: Mumbai  # keypair
        instance_type: "{{ ec2_instance_type }}"
        image_id: "{{ ec2_ami_id }}"
        region: "{{ aws_region }}"
        security_groups: ["{{ web_sg_name }}"]
        wait: yes
      register: ec2_instance

    - name: Set EC2 instance IP fact
      set_fact:
        ec2_ip: "{{ ec2_instance.instances[0].public_ip_address }}"

    - name: Output EC2 IP
      debug:
        msg: "EC2 Public IP: {{ ec2_ip }}"

